apt-get install         \
    asciidoc            \
    autoconf            \
    autotools-dev       \
    bison               \
    build-essential     \
    ccache              \
    cmake               \
    dejagnu             \
    dos2unix            \
    doxygen             \
    emacs               \
    expect              \
    exuberant-ctags     \
    flex                \
    git                 \
    gperf               \
    help2man            \
    htop                \
    ipython             \
    lcov                \
    libcap-dev          \
    libffi-dev          \
    libfuse-dev         \
    libgeos-dev         \
    libimlib2-dev       \
    liblua5.1-0-dev     \
    libmysqlclient-dev  \
    libncurses5-dev     \
    libpcap-dev         \
    libpcre3-dev        \
    libsctp-dev         \
    libsqlite3-dev      \
    libssl-dev          \
    libtool             \
    libunbound-dev      \
    libwbxml2-dev       \
    libxml2-dev         \
    libxmlsec1-dev      \
    lldb                \
    llvm                \
    llvm-dev            \
    lua5.1              \
    mtasc               \
    perl                \
    pulseaudio          \
    pylint              \
    python-dev          \
    python-pip          \
    python-psutil       \
    qt5-default         \
    rlwrap              \
    rtorrent            \
    ruby-dev            \
    scons               \
    smitools            \
    software-properties-common \
    source-highlight    \
    sudo                \
    subversion          \
    swfmill             \
    tcl8.5              \
    texinfo             \
    texlive-fonts-extra \
    tig                 \
    tmux                \
    tofrodos            \
    valgrind            \
    valgrind            \
    vim                 \
    vlc                 \
    xclip               \
    xfonts-terminus     \
    xsltproc            \
    zsh
