apt-get install         \
    dos2unix            \
    tofrodos            \
    libsctp-dev         \
    build-essential     \
    libmysqlclient-dev  \
    libgeos-dev         \
    flex                \
    gperf               \
    valgrind            \
    mtasc               \
    xsltproc            \
    swfmill             \
    git                 \
    vim                 \
    emacs               \
    libxml2-dev         \
    bison               \
    dejagnu             \
    tcl8.5              \
    expect              \
    perl                \
    autoconf            \
    autotools-dev       \
    libtool             \
    doxygen             \
    texinfo             \
    libffi-dev          \
    asciidoc            \
    libcap-dev          \
    lua5.1              \
    liblua5.1-dev       \
    libsqlite3-dev      \
    libfuse-dev         \
    libpcap-dev         \
    php5-dev            \
    ruby-dev            \
    python-dev          \
    scons               \
    libimlib2-dev       \
    libssl-dev          \
    libxmlsec1-dev      \
    libpcre3-dev        \
    libncurses5-dev     \
    source-highlight    \
    texlive-fonts-extra \
    exuberant-ctags     \
    smitools            \
    rlwrap              \
    xclip               \
    tig                 \
    ccache              \
    xfonts-terminus     \
    libwbxml2-dev       \
    npm                 \
    vlc
