apt install             \
    build-essential     \
    python3-ipython     \
    git                 \
    htop                \
    silversearcher-ag   \
    software-properties-common \
    tig                 \
    tmux                \
    vlc                 \
    xclip               \
    mosh                \
    meld                \
    arandr              \
    autorandr           \
    net-tools           \
    xfonts-terminus     \
    awesome             \
    neovim              \
    python3-neovim      \
    python-neovim       \
    gnome-screensaver   \
    sakura              \
    zstd                \
    blueman             \
    jq                  \
    awscli              \
    light               \
    zsh
