apt-get install         \
    asciidoc            \
    autoconf            \
    autotools-dev       \
    bison               \
    build-essential     \
    ccache              \
    clang               \
    cmake               \
    dos2unix            \
    doxygen             \
    exuberant-ctags     \
    flex                \
    git                 \
    gperf               \
    htop                \
    ipython             \
    lcov                \
    libclang-dev        \
    libssl-dev          \
    libtool             \
    lldb                \
    llvm                \
    llvm-dev            \
    perl                \
    pulseaudio          \
    python-dev          \
    python-pip          \
    python3-dev         \
    python3-pip         \
    qt5-default         \
    silversearcher-ag   \
    software-properties-common \
    source-highlight    \
    subversion          \
    sudo                \
    tig                 \
    tmux                \
    valgrind            \
    vim                 \
    vlc                 \
    xclip               \
    xfonts-terminus     \
    zsh
