apt install             \
    build-essential     \
    python3.7           \
    python3-ipython     \
    python2.7           \
    git                 \
    htop                \
    silversearcher-ag   \
    software-properties-common \
    tig                 \
    tmux                \
    neovim              \
    vlc                 \
    xclip               \
    xblacklight         \
    mosh                \
    alsa-utils          \
    meld                \
    arandr              \
    autoranr            \
    net-tools           \
    xfonts-terminus     \
    awesome             \
    neovim              \
    python3-neovim      \
    python-neovim       \
    gnome-screensaver   \
    sakura              \
    zsh
