dnf install \
  autoconf            \
  awesome             \
  ccache              \
  chromium            \
  konsole             \
  qutebrowser         \
  qt5                 \
  qt5-devel           \
  neovim              \
  python2-neovim      \
  python3-neovim      \
  cmake               \
  cmake               \
  ctags               \
  git                 \
  libtool             \
  lldb                \
  lcov                \
  llvm                \
  htop                \
  pylint              \
  python-pip          \
  clang               \
  ipython             \
  zsh                 \
  tig                 \
  tmux                \
  valgrind
