" Moeryn's nvim configuration

" This makes neovim more responsive with tmux
set ttimeout
set ttimeoutlen=0

" {{{ Neomake

let g:syntastic_python_checkers = ['']
let g:neomake_python_enable_makers = ['pylint']
let g:neomake_javascript_enable_makers = ['jshint']
let g:neomake_open_list=1
let g:neomake_serialize_abort_on_error=1
let g:neomake_serialize=1
autocmd BufWritePost *.py :Neomake pylint
autocmd BufWritePost *.js :Neomake jshint

" }}}
" {{{ Terminal & Neoterm

" escape
tnoremap <esc> <C-\><C-n>

" move from terminal to other pane
tnoremap <C-h> <C-\><C-n><C-w>h
tnoremap <C-j> <C-\><C-n><C-w>j
tnoremap <C-k> <C-\><C-n><C-w>k
tnoremap <C-l> <C-\><C-n><C-w>l

" always be in insert mode when entering terminal
autocmd BufWinEnter,WinEnter term://* startinsert

" always leave insert mode when leaving terminal
autocmd BufLeave term://* stopinsert

" Neoterm

let g:neoterm_position = 'vertical'
let g:neoterm_automap_keys = ',tt'

" Useful maps
" hide/close all terminals
nnoremap <silent> ,th :call neoterm#close_all()<cr>
" clear terminal
nnoremap <silent> ,tl :call neoterm#clear()<cr>
" kills the current job (send a <c-c>)
nnoremap <silent> ,tc :call neoterm#kill()<cr>

" Git commands
command! -nargs=+ Tg :T git <args>

" }}}
