export GIT_PS1_SHOWSTASHSTATE=1
export PS1='\[\e[34;1m\]\u@\[\e[32;1m\]\H:\[\e[31;1m\]$(__git_ps1) \[\e[0m\]\w\[\e[31;1m\]\$ \[\e[0m\]'

source ~/CONFIG/bash/liquidpromptrc
source ~/CONFIG/submodules/liquidpromt/liquidprompt

# Use bash completion, if installed
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

source ~/CONFIG/submodules/git/contrib/completion/git-completion.bash
source ~/CONFIG/submodules/git/contrib/completion/git-prompt.sh

source ~/CONFIG/bash/moerynrc
